version: '3'

services:
  market-api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8888:8080
  
  market-web:
    image: php:7-apache
    volumes:
      - ./web:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - market-api